// Generated by gencpp from file mofs/FuzzyControl_IORequest.msg
// DO NOT EDIT!


#ifndef MOFS_MESSAGE_FUZZYCONTROL_IOREQUEST_H
#define MOFS_MESSAGE_FUZZYCONTROL_IOREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mofs
{
template <class ContainerAllocator>
struct FuzzyControl_IORequest_
{
  typedef FuzzyControl_IORequest_<ContainerAllocator> Type;

  FuzzyControl_IORequest_()
    : inputs()  {
      inputs.assign(0.0);
  }
  FuzzyControl_IORequest_(const ContainerAllocator& _alloc)
    : inputs()  {
      inputs.assign(0.0);
  }



   typedef boost::array<float, 3>  _inputs_type;
  _inputs_type inputs;




  typedef boost::shared_ptr< ::mofs::FuzzyControl_IORequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mofs::FuzzyControl_IORequest_<ContainerAllocator> const> ConstPtr;

}; // struct FuzzyControl_IORequest_

typedef ::mofs::FuzzyControl_IORequest_<std::allocator<void> > FuzzyControl_IORequest;

typedef boost::shared_ptr< ::mofs::FuzzyControl_IORequest > FuzzyControl_IORequestPtr;
typedef boost::shared_ptr< ::mofs::FuzzyControl_IORequest const> FuzzyControl_IORequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mofs::FuzzyControl_IORequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mofs::FuzzyControl_IORequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace mofs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'mofs': ['/home/andrew/catkin_ws/src/mofs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::mofs::FuzzyControl_IORequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mofs::FuzzyControl_IORequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mofs::FuzzyControl_IORequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mofs::FuzzyControl_IORequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mofs::FuzzyControl_IORequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mofs::FuzzyControl_IORequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mofs::FuzzyControl_IORequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ea0b038bccdff67bc1751623cde4aed3";
  }

  static const char* value(const ::mofs::FuzzyControl_IORequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xea0b038bccdff67bULL;
  static const uint64_t static_value2 = 0xc1751623cde4aed3ULL;
};

template<class ContainerAllocator>
struct DataType< ::mofs::FuzzyControl_IORequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mofs/FuzzyControl_IORequest";
  }

  static const char* value(const ::mofs::FuzzyControl_IORequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mofs::FuzzyControl_IORequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
float32[3] inputs\n\
";
  }

  static const char* value(const ::mofs::FuzzyControl_IORequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mofs::FuzzyControl_IORequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.inputs);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct FuzzyControl_IORequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mofs::FuzzyControl_IORequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mofs::FuzzyControl_IORequest_<ContainerAllocator>& v)
  {
    s << indent << "inputs[]" << std::endl;
    for (size_t i = 0; i < v.inputs.size(); ++i)
    {
      s << indent << "  inputs[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.inputs[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOFS_MESSAGE_FUZZYCONTROL_IOREQUEST_H
