// Generated by gencpp from file mofs/FuzzyControl_IOResponse.msg
// DO NOT EDIT!


#ifndef MOFS_MESSAGE_FUZZYCONTROL_IORESPONSE_H
#define MOFS_MESSAGE_FUZZYCONTROL_IORESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mofs
{
template <class ContainerAllocator>
struct FuzzyControl_IOResponse_
{
  typedef FuzzyControl_IOResponse_<ContainerAllocator> Type;

  FuzzyControl_IOResponse_()
    : output(0.0)  {
    }
  FuzzyControl_IOResponse_(const ContainerAllocator& _alloc)
    : output(0.0)  {
    }



   typedef float _output_type;
  _output_type output;




  typedef boost::shared_ptr< ::mofs::FuzzyControl_IOResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mofs::FuzzyControl_IOResponse_<ContainerAllocator> const> ConstPtr;

}; // struct FuzzyControl_IOResponse_

typedef ::mofs::FuzzyControl_IOResponse_<std::allocator<void> > FuzzyControl_IOResponse;

typedef boost::shared_ptr< ::mofs::FuzzyControl_IOResponse > FuzzyControl_IOResponsePtr;
typedef boost::shared_ptr< ::mofs::FuzzyControl_IOResponse const> FuzzyControl_IOResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mofs::FuzzyControl_IOResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mofs::FuzzyControl_IOResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace mofs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'mofs': ['/home/andrew/catkin_ws/src/mofs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::mofs::FuzzyControl_IOResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mofs::FuzzyControl_IOResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mofs::FuzzyControl_IOResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mofs::FuzzyControl_IOResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mofs::FuzzyControl_IOResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mofs::FuzzyControl_IOResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mofs::FuzzyControl_IOResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dc04e8385a5c2f792e8299232db8e2eb";
  }

  static const char* value(const ::mofs::FuzzyControl_IOResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xdc04e8385a5c2f79ULL;
  static const uint64_t static_value2 = 0x2e8299232db8e2ebULL;
};

template<class ContainerAllocator>
struct DataType< ::mofs::FuzzyControl_IOResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mofs/FuzzyControl_IOResponse";
  }

  static const char* value(const ::mofs::FuzzyControl_IOResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mofs::FuzzyControl_IOResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 output\n\
\n\
";
  }

  static const char* value(const ::mofs::FuzzyControl_IOResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mofs::FuzzyControl_IOResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.output);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct FuzzyControl_IOResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mofs::FuzzyControl_IOResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mofs::FuzzyControl_IOResponse_<ContainerAllocator>& v)
  {
    s << indent << "output: ";
    Printer<float>::stream(s, indent + "  ", v.output);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOFS_MESSAGE_FUZZYCONTROL_IORESPONSE_H
