(cl:defpackage mofs-srv
  (:use )
  (:export
   "FUZZYCONTROL_4_IO"
   "<FUZZYCONTROL_4_IO-REQUEST>"
   "FUZZYCONTROL_4_IO-REQUEST"
   "<FUZZYCONTROL_4_IO-RESPONSE>"
   "FUZZYCONTROL_4_IO-RESPONSE"
   "FUZZYCONTROL_IO"
   "<FUZZYCONTROL_IO-REQUEST>"
   "FUZZYCONTROL_IO-REQUEST"
   "<FUZZYCONTROL_IO-RESPONSE>"
   "FUZZYCONTROL_IO-RESPONSE"
  ))

