// Generated by gencpp from file aruco/DetectedMarkerArray.msg
// DO NOT EDIT!


#ifndef ARUCO_MESSAGE_DETECTEDMARKERARRAY_H
#define ARUCO_MESSAGE_DETECTEDMARKERARRAY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <aruco/DetectedMarker.h>

namespace aruco
{
template <class ContainerAllocator>
struct DetectedMarkerArray_
{
  typedef DetectedMarkerArray_<ContainerAllocator> Type;

  DetectedMarkerArray_()
    : markers()  {
    }
  DetectedMarkerArray_(const ContainerAllocator& _alloc)
    : markers(_alloc)  {
    }



   typedef std::vector< ::aruco::DetectedMarker_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::aruco::DetectedMarker_<ContainerAllocator> >::other >  _markers_type;
  _markers_type markers;




  typedef boost::shared_ptr< ::aruco::DetectedMarkerArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::aruco::DetectedMarkerArray_<ContainerAllocator> const> ConstPtr;

}; // struct DetectedMarkerArray_

typedef ::aruco::DetectedMarkerArray_<std::allocator<void> > DetectedMarkerArray;

typedef boost::shared_ptr< ::aruco::DetectedMarkerArray > DetectedMarkerArrayPtr;
typedef boost::shared_ptr< ::aruco::DetectedMarkerArray const> DetectedMarkerArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::aruco::DetectedMarkerArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::aruco::DetectedMarkerArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace aruco

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'aruco': ['/home/andrew/catkin_ws/src/aruco/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::aruco::DetectedMarkerArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::aruco::DetectedMarkerArray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::aruco::DetectedMarkerArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::aruco::DetectedMarkerArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::aruco::DetectedMarkerArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::aruco::DetectedMarkerArray_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::aruco::DetectedMarkerArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5b14ecbc39d258014a7e7c8e73c5ee55";
  }

  static const char* value(const ::aruco::DetectedMarkerArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5b14ecbc39d25801ULL;
  static const uint64_t static_value2 = 0x4a7e7c8e73c5ee55ULL;
};

template<class ContainerAllocator>
struct DataType< ::aruco::DetectedMarkerArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "aruco/DetectedMarkerArray";
  }

  static const char* value(const ::aruco::DetectedMarkerArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::aruco::DetectedMarkerArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "aruco/DetectedMarker[] markers\n\
================================================================================\n\
MSG: aruco/DetectedMarker\n\
int32 id\n\
geometry_msgs/PoseStamped pose\n\
================================================================================\n\
MSG: geometry_msgs/PoseStamped\n\
# A Pose with reference coordinate frame and timestamp\n\
Header header\n\
Pose pose\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of postion and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
";
  }

  static const char* value(const ::aruco::DetectedMarkerArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::aruco::DetectedMarkerArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.markers);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct DetectedMarkerArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::aruco::DetectedMarkerArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::aruco::DetectedMarkerArray_<ContainerAllocator>& v)
  {
    s << indent << "markers[]" << std::endl;
    for (size_t i = 0; i < v.markers.size(); ++i)
    {
      s << indent << "  markers[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::aruco::DetectedMarker_<ContainerAllocator> >::stream(s, indent + "    ", v.markers[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ARUCO_MESSAGE_DETECTEDMARKERARRAY_H
