// Generated by gencpp from file vision_control_4_uav/codeCommand.msg
// DO NOT EDIT!


#ifndef VISION_CONTROL_4_UAV_MESSAGE_CODECOMMAND_H
#define VISION_CONTROL_4_UAV_MESSAGE_CODECOMMAND_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace vision_control_4_uav
{
template <class ContainerAllocator>
struct codeCommand_
{
  typedef codeCommand_<ContainerAllocator> Type;

  codeCommand_()
    : code(0)  {
    }
  codeCommand_(const ContainerAllocator& _alloc)
    : code(0)  {
    }



   typedef int32_t _code_type;
  _code_type code;




  typedef boost::shared_ptr< ::vision_control_4_uav::codeCommand_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::vision_control_4_uav::codeCommand_<ContainerAllocator> const> ConstPtr;

}; // struct codeCommand_

typedef ::vision_control_4_uav::codeCommand_<std::allocator<void> > codeCommand;

typedef boost::shared_ptr< ::vision_control_4_uav::codeCommand > codeCommandPtr;
typedef boost::shared_ptr< ::vision_control_4_uav::codeCommand const> codeCommandConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::vision_control_4_uav::codeCommand_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::vision_control_4_uav::codeCommand_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace vision_control_4_uav

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'vision_control_4_uav': ['/home/andrew/catkin_ws/src/vision_control_4_uav/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::vision_control_4_uav::codeCommand_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vision_control_4_uav::codeCommand_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vision_control_4_uav::codeCommand_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vision_control_4_uav::codeCommand_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vision_control_4_uav::codeCommand_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vision_control_4_uav::codeCommand_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::vision_control_4_uav::codeCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5e8de1acec506dc927ef4d2e8193b594";
  }

  static const char* value(const ::vision_control_4_uav::codeCommand_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5e8de1acec506dc9ULL;
  static const uint64_t static_value2 = 0x27ef4d2e8193b594ULL;
};

template<class ContainerAllocator>
struct DataType< ::vision_control_4_uav::codeCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "vision_control_4_uav/codeCommand";
  }

  static const char* value(const ::vision_control_4_uav::codeCommand_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::vision_control_4_uav::codeCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#0: means hover, 1: follow the last code deteted, other number: follow this specific code\n\
int32 code\n\
";
  }

  static const char* value(const ::vision_control_4_uav::codeCommand_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::vision_control_4_uav::codeCommand_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.code);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct codeCommand_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::vision_control_4_uav::codeCommand_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::vision_control_4_uav::codeCommand_<ContainerAllocator>& v)
  {
    s << indent << "code: ";
    Printer<int32_t>::stream(s, indent + "  ", v.code);
  }
};

} // namespace message_operations
} // namespace ros

#endif // VISION_CONTROL_4_UAV_MESSAGE_CODECOMMAND_H
