(cl:defpackage vrep_common-msg
  (:use )
  (:export
   "<PROXIMITYSENSORDATA>"
   "PROXIMITYSENSORDATA"
   "<JOINTSETSTATEDATA>"
   "JOINTSETSTATEDATA"
   "<FORCESENSORDATA>"
   "FORCESENSORDATA"
   "<VISIONSENSORDATA>"
   "VISIONSENSORDATA"
   "<VISIONSENSORDEPTHBUFF>"
   "VISIONSENSORDEPTHBUFF"
   "<OBJECTGROUPDATA>"
   "OBJECTGROUPDATA"
   "<VREPINFO>"
   "VREPINFO"
  ))

